version: "3.7"
services:
  db:
    platform: linux/x86_64    # M1
    image: mysql:5.7
    restart: always
    container_name: board
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=board
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
