version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    command: --lower_case_table_names=1
    container_name: board
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=board
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
